### ISSUE TITLE
补充虚拟桌面实验“Linux入门”中的内容

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#445]
参考 https://www.shiyanlou.com/courses/1 ，组织虚拟桌面实验中 “Linux 入门课程”的实验。

@milanlanlan 在后台 http://a002.nscc-gz.cn:10165/admin/vnc_lab/ 添加实验内容（我已经添加了 4 个不完整的示例，你完善后，再添加其他的小任务）。

有疑问可以在下面评论。

**Comment by milanlanlan** [comment]
好的，不过我可能必须先写完论文的初稿再开始添加，老师催得有点紧

**Comment by xuelangZF** [comment]
随你喽

**Comment by xuelangZF** [comment]
不要直接抄 shiyanlou 的内容。特别注意不要使用带有水印logo 的实验楼中的图片。  @milanlanlan

**Comment by milanlanlan** [comment]
收到，刚刚在公教身边没有电脑

**Comment by milanlanlan** [comment]
最近两天网站都上不去，是因为超算关了端口吗？

**Comment by xuelangZF** [comment]
嗯嗯，刚才发邮件问那边了。

**Comment by xuelangZF** [comment]
@milanlanlan  站点已经恢复，可以补充内容了。

**Comment by milanlanlan** [comment]
好的，我补充了前两个，发现这个课程的内容太多了，不是很好写，但是抄的话会不会有版权问题？（毕竟全文脉络差不多，只改了措辞的话还是很明显）
目前我把涉及实验楼的部分都删掉了

**Comment by xuelangZF** [comment]
@milanlanlan 

实验楼的确实不能抄。这样吧，你看下 [《鸟哥的私房菜》](https://wizardforcel.gitbooks.io/vbird-linux-basic-4e/content/index.html)，这个没有版权争议。

然后参考上面的gitbook，至少把 3，4，6，7，8 章节的内容整理一下。注意合理使用 Markdown 格式，加图片，高亮等（gitbook其实就是用的markdown格式）。

**Comment by milanlanlan** [comment]
这个我也考虑过，不过我发现这个不仅仅只有电子版，也出了实体书籍（哲鹏师兄就有这本书），这样的话真的不会有版权争议吗？我担心用了之后实验楼和这本书一起犯难，感觉会更加麻烦。。
如果不会的话，我就把之前的删掉然后把这本书放上来吧

**Comment by xuelangZF** [comment]
这个就不用考虑版权的问题了，本来鸟哥这个网上一搜一大堆，咱们这个又不是盈利目的，所以不会有事的。

此外，你整理的时候，也还是要删减些内容的，不然太多了。

**Comment by milanlanlan** [comment]
好的

**Comment by xuelangZF** [comment]
目前只有 6 个，你觉得够了吗？  @milanlanlan

**Comment by milanlanlan** [comment]
所以我现在正在写啊。请问我有说够了吗？

**Comment by xuelangZF** [comment]
👌，一周至少5个吧，你的进度太慢，又不给我沟通，我以为你写完了。

**Comment by milanlanlan** [comment]
好的，我今晚就继续添加
