### ISSUE TITLE
机时申请表单设计与实现的讨论

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#478]
添加超算机时申请入口，提供一个表单，供用户填写申请。后台将申请发送到各超算中心的接口。

<img width="416" alt="2017-04-28 4 22 01" src="https://cloud.githubusercontent.com/assets/2769831/25520555/df2b8478-2c2e-11e7-8313-5234b21bbd35.png">

@luozhx  先负责前端表单创建，对于接收到的数据怎么处理，目前先不管。

**Comment by xuelangZF** [comment]
学校的 USC 有一个很好的系统， 值得学习。

http://usc.sysu.edu.cn/taskcenter/workflow/index

**Comment by xuelangZF** [comment]
前端部分（@ym13349140 负责）：

1. 主要是在顶部菜单栏目添加`机时申请`入口；
2. 进入机时申请页面，可以看到机时申请的一个说明（先留出位置），然后有一个申请的按钮；
3. 申请按钮进去的是一个表单页面（表单样式参考USC），稍后我会上传一个图片，说明填写哪些内容。

后台部分（ @luozhx 负责）：

1. 由后台一个入口（类似 /admin 这样的url），输入机时管理员账户、密码，进入管理页面。
2. 管理员可以看到目前所有的申请记录，可以下载PDF格式的申请表。
3. 管理员选择批准机时申请后，会进入一个页面，供管理员上传私钥和密码等登录需要的信息。
4. 系统自动发送邮件给申请机时者（邮件包含了管理员上传的密钥等信息）。
5. 后台在数据表中保存高性能计算机密钥和申请记录之间的对应关系。

数据库设计部分，需要2张表：

1. 申请信息表：包括了申请需要填写的信息，和用户表是一对一的关系，一个用户对应一个申请记录；还包括申请目前的状态，是`通过申请`，还是`正在处理中`，还是`申请被拒绝`？
2. 账户关联表：保存高性能计算记得密钥和密码等信息，和申请记录是一对一的关系，每个账户关联表对应一个申请信息记录。

**Comment by luozhx** [comment]
申请表和用户不是多对一吗？一个用户应该可以申请多次吧。

**Comment by xuelangZF** [comment]
嗯，也是，申请的用完了还可以再申请的。这里改为 一对多 吧。

**Comment by ym13349140** [comment]
师兄，已经提交了的申请还需要提供修改功能吗？

**Comment by xuelangZF** [comment]
直接在开发群问一下吧

**Comment by xuelangZF** [comment]
注册用户和超算用户之间 一对一 ，一个用户不能申请多个超算账户。

机时用完后，可以再次申请。

暂时不用提供修改功能吧，不过系统可以保存用户申请时填写的信息。用户可以编辑一点，然后点`保存`，下次进入后，直接加载出上次保存的内容。
