### ISSUE TITLE
程序运行状态反馈

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#481]
从后台获取程序运行状态（询问 @milanlanlan  或者 @Zouzhp3 ），然后在前端显示。

@ym13349140 负责

**Comment by xuelangZF** [comment]
目前 @milanlanlan  已经改完了基本的后台和前端，需要完善其中 反馈状态的 modal 展示部分。

建议还是用目前的图片，只是去掉上面的字。然后在状态更新时，在 modal 中添加相应的文字信息。（文字信息在图片的上面，用 z-index 设置或者其他方法。）

**Comment by ym13349140** [comment]
OK~
