### ISSUE TITLE
数据库的主从备份

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#516]
@wzl281158150  在自己的 vps 上做一下主从备份的流程，然后更新 [wiki](https://github.com/xuelangZF/ehpc/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E4%B8%BB%E4%BB%8E%E5%A4%87%E4%BB%BD)。

之后云主机恢复后，由 @Zouzhp3  在服务器进行相应的操作。

相关资料：

[Ubuntu实时备份](https://www.timelog.xyz/tmv/4.html)    
[MySQL数据库复制、镜像、实时备份](http://www.huangzhong.ca/zh/mysql-database-replication-mirroring-real-time/#comments)

**Comment by wzl281158150** [comment]
vps不足

**Comment by xuelangZF** [comment]
你只有一个吗？或者去问 柯老师从实验室要两台虚拟机。

**Comment by wzl281158150** [comment]
ubuntu试试备份也要弄吗？ 还是只做数据库?

**Comment by xuelangZF** [comment]
只用数据库的，文件系统备份已经做了。

**Comment by xuelangZF** [comment]
1、2 步是在主服务器做的操作吧。

**Comment by xuelangZF** [comment]
@Zouzhp3 等服务器恢复后，进行主从备份。

**Comment by wzl281158150** [comment]
@xuelangZF 已修改

**Comment by Zouzhp3** [comment]
OK
