### ISSUE TITLE
实现站内通知

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#542]
https://github.com/luozhx/ehpc/issues/541#issue-232417937 中需要一个站内通知模块，类似Github这种。

![image](https://cloud.githubusercontent.com/assets/2769831/26610183/a2986b5c-45d8-11e7-81a3-e0f69bc6dc0f.png)

建议 @wzl281158150  先设计好提醒的数据库实体，至少包括：

```
发送者
接收者
时间
是否已读（显示已读提醒、未读提醒）
事件名称
事件链接
...
```

然后考虑什么时候生成通知信息，如何判断通知信息已读等问题。想好思路之后，在下面写出来，我们讨论下合适的话再写代码。

**Comment by Zouzhp3** [comment]
这里站内通知可以等到管理页面重构完成后再写，我所用的后台管理模板也提供了站内通知的功能。

**Comment by xuelangZF** [comment]
管理模板的站内通知 和 这里的站内通知并没有直接依赖关系吧。 这里把站内通知接口搭建好，后台管理中可以直接使用的。

**Comment by xuelangZF** [comment]
@wzl281158150  做到什么程度了？

**Comment by wzl281158150** [comment]
后台写完了，今天按照新的模板写一下前端入口

**Comment by wzl281158150** [comment]
就目前来说，仅仅只有管理页面或者教师页面拥有读取消息入口，学生用户是否需要消息读取入口

**Comment by xuelangZF** [comment]
需要的，因为评论系统中有 @ 某人的功能，。

并且后期，老师可以发送消息给学生，这时候也可以通知。

**Comment by wzl281158150** [comment]
也就是说，我还需要他提供查看页面、发送页面等内容？

**Comment by xuelangZF** [comment]
发送页面是什么意思？

**Comment by wzl281158150** [comment]
就是比如老师要发消息，要给一个页面让他写内容发送

**Comment by xuelangZF** [comment]
这个先不做吧。  目前的通知，主要是 @ 的通知，还有有学生加入课程时，给老师的通知。 其他的等后期老师需要的话再加。

**Comment by xuelangZF** [comment]
通知这里，感觉好像偏离了方向，我们目前要做的是

1. 学生申请加入课程时，会给老师发送提醒。老师可以通过右上角的 信息 入口，看到信息列表。类似下面：

![image](https://user-images.githubusercontent.com/2769831/27011569-9e0fc348-4ef0-11e7-94b1-e154b32beb67.png)

提醒中包括链接，可以让老师快速定位到需要进行操作的页面（用户管理页面，最好是能够直接显示所有未批准的申请）。

2. 用户a  @ b时，b 也会收到通知。用户b的通知图标中也有信息提示，点击后出现类似老师的列表，其中有多条信息。

**Comment by wzl281158150** [comment]
发送了提醒，可在右上角图标处进入，同时提供了后台发送通知函数，可自行调用

**Comment by wzl281158150** [comment]
老师点击图标后也的确 可以看见信息列表

**Comment by wzl281158150** [comment]
关于用户@功能，对应开发人员可在写入数据库部分自行调用 发送消息函数 该函数处于 util文件夹中的notifications.py中
