### ISSUE TITLE
作业部分：未提交作业的显示

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#546]
在学生的作业列表中，用颜色标注学生是否已经提交了该作业。对于已经提交的作业，可以考虑用绿色背景色，过了截止日期没有提交的作业，用红色标注，没有到截止时间的作业，不用标注。

![image](https://cloud.githubusercontent.com/assets/2769831/26629591/9a71d974-4635-11e7-83b5-6fbf9aebb99c.png)

PS：作业列表那么长，里面还可以加些信息，比如 `截止时间`。

教师端，能够列出（支持导出）所有目前还没有提交作业的同学。

@ym13349140

**Comment by xuelangZF** [comment]
没有加入课程的话，不要显示 `未提交` 吧。

![image](https://user-images.githubusercontent.com/2769831/26928663-88751c86-4c89-11e7-9c00-43cf2291bbc1.png)

还有，如果没有加入课程的话，点击某个作业，最好是 modal 显示，加入课程后，才能看到作业。不是现在的样子（这时候，只能刷新页面，才能看到作业列表）

![image](https://user-images.githubusercontent.com/2769831/26928725-b3a5144c-4c89-11e7-8083-a81487b9a8ab.png)

**Comment by ym13349140** [comment]
这个课程本来就是公开的课程，就是不用加入课程也可以访问所有课程资源的吧，如果是要限制加入了课程才能提交的话一般就直接设置课程为私有的吧？

**Comment by xuelangZF** [comment]
嗯，公开课程作业应该是可以看到的。（现在公开课只能看到作业列表，点开后就显示上面的`请先加入课程才能查看作业！`）

**Comment by ym13349140** [comment]
噢噢，好吧~

**Comment by xuelangZF** [comment]
公开课的话，作业全部看得到，然后也可以看自己的提交状态吧。（除了颜色，最好在图标前面加上文字描述）

![image](https://user-images.githubusercontent.com/2769831/26962764-144bf356-4d1b-11e7-959d-1deca2cfb7c7.png)

**Comment by ym13349140** [comment]
提交状态也是要加入课程之后才能有的吧？

**Comment by xuelangZF** [comment]
对对对的
