### ISSUE TITLE
实验进度部分页面样式错误

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#548]
如图所示：

![2017-05-31 9 38 26](https://cloud.githubusercontent.com/assets/2769831/26634709/0c7aacd0-464a-11e7-8d38-1a239a6dc6f5.png)

@Zouzhp3 修复。（低优先级）

**Comment by Zouzhp3** [comment]
这里是哪里样式有问题？

**Comment by xuelangZF** [comment]
提示信息顶部应该和 虚拟实验室的顶部一样的

**Comment by luozhx** [comment]
#577 已修复
