### ISSUE TITLE
管理页面重构

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#554]
https://github.com/luozhx/ehpc/issues/541 中管理页面重构。

左侧菜单分为三级菜单：

```
课程管理 
    MPI 编程（右边对应课程信息的编辑）
        课程图片
        课时管理
        权限管理
        成员管理
        ....
     OpenMP 编程
        课程图片
        课时管理
        权限管理
        成员管理
        ....

题目管理
      并行计算基础
        选择
        填空
        ...
      并行算法理论

实验管理
      MPI 编程实训（对应编辑信息的页面）
          实验任务列表
      OpenMP 编程实训	
          实验任务列表
      Linux 基础入门
          实验任务列表

知识点管理
      并行算法理论
      并行计算基础
```

**Comment by Zouzhp3** [comment]
所以菜单还是要读取所有课程的课程名、所有题目的名称、所有实验的名称、所有知识点的名称对吗？

**Comment by Zouzhp3** [comment]
已经完成了初步的重构，等吴老师看后再进行下一版的修改。

**Comment by xuelangZF** [comment]
可以，是需要读那些信息，存到 g 全局变量吧

**Comment by xuelangZF** [comment]
删除掉 ✉️ 吧，只留一个  `通知` 的图标备用（等 @王泽龙 做好通知接口后，在这里添加）。**切换为学生**的链接地址换掉。

![2017-06-08 8 40 01](https://user-images.githubusercontent.com/2769831/26929029-cbfa3aa8-4c8a-11e7-9f0f-a9c8abd143a0.png)

左侧课程管理下面直接是课程就行了，不用课程列表，如下（题目管理也类似）。

![2017-06-08 8 41 02](https://user-images.githubusercontent.com/2769831/26929027-c9b42fb0-4c8a-11e7-8eb9-082344ee18c4.png)

**Comment by xuelangZF** [comment]
下一步 在右侧列表中，删除 左侧的入口链接地址。只保留核心操作区域（最好做到屏幕适配）。

![image](https://user-images.githubusercontent.com/2769831/26929904-ff9b4354-4c8d-11e7-93d2-33c119d4af60.png)
