### ISSUE TITLE
丢失部分作业

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#558]
学生提交作业后，数据库记录已经提交，但是后台文件系统中丢失了学生的作业。

在保存数据库记录前，先**检查相应目录是否有该同学本次提交的作业**，有的话，再保存数据库记录。

@ym13349140 修复。

**Comment by ym13349140** [comment]
原来的逻辑本来就是upload_file成功之后才会在数据库增加相应记录：
![image](https://user-images.githubusercontent.com/17507937/26962849-a58bdc14-4d1b-11e7-90cd-c84e7a5dc61e.png)
我看了upload_file函数，这里是save之后就返回了true，我在想会不会有可能是文件还没保存完就先返回true了？
![image](https://user-images.githubusercontent.com/17507937/26962877-d2642002-4d1b-11e7-92c0-763219dd816d.png)

我现在在写数据库之前增加了一个循环，判断文件目录下有了相应的文件才开始写数据库，不知道这样能不能解决问题。

**Comment by xuelangZF** [comment]
这样也不合适，万一上传失败，一直没文件，循环这里就会死掉吧。

不要用循环去检查，在 upload_file 中，返回 True 之前，先用 os.path.isfile(path) 判断文件是否存在，存在的话，返回 True，否则返回 False。

这样的好处，就是其他地方都不用改。

**Comment by ym13349140** [comment]
在upload_file返回 True 之前，先用 os.path.isfile(path) 判断一次文件是否存在的话，会不会检查的时候文件还没写完，结果返回了false，但是其实最后文件写入成功了？

**Comment by xuelangZF** [comment]
文档在这里：

http://werkzeug.pocoo.org/docs/0.12/datastructures/#werkzeug.datastructures.FileStorage.save

save 函数实现：

https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py#L2682

其中用到  shutil.copyfileobj，

> shutil.copyfileobj(fsrc, fdst[, length])
> Copy the contents of the file-like object fsrc to the file-like object fdst. The integer length, if given, is the buffer size. In particular, a negative length value means to copy the data without looping over the source data in chunks; by default the data is read in chunks to avoid uncontrolled memory consumption. Note that if the current file position of the fsrc object is not 0, only the contents from the current file position to the end of the file will be copied.

copyfileobj 要不成功，要不返回异常，是阻塞操作。

这里 save 会一直等待操作完成的。

**Comment by ym13349140** [comment]
噢噢，好的~
